"""
Tweek Docker Bridge

Lightweight integration with Docker for container-level isolation.
Generates docker-compose.yaml and provides simple run/status commands.
Delegates actual container management to Docker rather than reimplementing.
"""

import subprocess
import textwrap
from pathlib import Path
from typing import Optional


TWEEK_HOME = Path.home() / ".tweek"


class DockerBridge:
    """Lightweight Docker integration for project-level container isolation."""

    def is_docker_available(self) -> bool:
        """Check if Docker is installed and the daemon is running."""
        try:
            result = subprocess.run(
                ["docker", "info"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def get_docker_version(self) -> Optional[str]:
        """Get Docker version string, or None if unavailable."""
        try:
            result = subprocess.run(
                ["docker", "version", "--format", "{{.Server.Version}}"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            if result.returncode == 0:
                return result.stdout.strip()
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass
        return None

    def init(self, project_dir: Path) -> Path:
        """Generate docker-compose.yaml for this project.

        Creates a minimal Docker Compose configuration that:
        - Mounts the project directory read-write at /workspace
        - Mounts global Tweek config read-only
        - Disables network access by default
        - Sets up environment for Tweek hooks

        Returns the path to the generated compose file.
        """
        project_dir = project_dir.resolve()
        tweek_dir = project_dir / ".tweek"
        tweek_dir.mkdir(parents=True, exist_ok=True)

        compose_path = tweek_dir / "docker-compose.yaml"
        tweek_home_str = str(TWEEK_HOME)

        compose_content = textwrap.dedent(f"""\
            # Tweek Docker Sandbox Configuration
            # Generated by: tweek sandbox docker init
            # Docs: https://github.com/your-org/tweek
            #
            # This file mounts your project into a container with Tweek hooks active.
            # Customize as needed for your workflow.

            services:
              tweek-sandbox:
                image: python:3.12-slim
                working_dir: /workspace
                volumes:
                  # Project directory (read-write)
                  - {project_dir}:/workspace:rw
                  # Global Tweek config (read-only)
                  - {tweek_home_str}:/home/tweek/.tweek-global:ro
                network_mode: "none"  # No network by default (security)
                environment:
                  - TWEEK_SANDBOX_LAYER=2
                  - TWEEK_GLOBAL_CONFIG=/home/tweek/.tweek-global
                  - HOME=/home/tweek
                # Install tweek and start a shell
                # Customize this command for your workflow
                command: >
                  bash -c "
                    pip install -q tweek 2>/dev/null;
                    echo 'Tweek sandbox ready. Project mounted at /workspace';
                    exec bash
                  "
                stdin_open: true
                tty: true
        """)

        compose_path.write_text(compose_content)
        return compose_path

    def run(self, project_dir: Path) -> int:
        """Launch the project in a Docker container.

        Returns the container's exit code.
        """
        project_dir = project_dir.resolve()
        compose_path = project_dir / ".tweek" / "docker-compose.yaml"

        if not compose_path.exists():
            # Auto-generate if not present
            self.init(project_dir)

        result = subprocess.run(
            ["docker", "compose", "-f", str(compose_path), "run", "--rm", "tweek-sandbox"],
            cwd=str(project_dir),
        )
        return result.returncode

    def stop(self, project_dir: Path) -> None:
        """Stop any running containers for this project."""
        compose_path = project_dir.resolve() / ".tweek" / "docker-compose.yaml"
        if compose_path.exists():
            subprocess.run(
                ["docker", "compose", "-f", str(compose_path), "down"],
                capture_output=True,
            )

    def suggest_docker(self, project_dir: Path) -> Optional[str]:
        """Return a suggestion message if Docker is available but not configured."""
        if not self.is_docker_available():
            return None

        compose = project_dir / ".tweek" / "docker-compose.yaml"
        if compose.exists():
            return None

        return (
            "Docker detected. For container-level isolation, run:\n"
            "  tweek sandbox docker init"
        )
