"""
Internal license key generation — NOT part of the client distribution.

This module exists solely for testing and admin use. In production,
license keys are generated by the license server (services/license-server/).
"""

import base64
import hashlib
import hmac
import json
import time
from typing import Optional, List

from tweek.licensing import Tier, LICENSE_SECRET


def generate_license_key(
    tier: Tier,
    email: str,
    expires_at: Optional[int] = None,
    features: Optional[List[str]] = None,
) -> str:
    """
    Generate a license key (admin/test use only).

    Args:
        tier: License tier
        email: Customer email
        expires_at: Expiration timestamp (None = never)
        features: Additional feature flags

    Returns:
        License key string
    """
    payload = {
        "tier": tier.value,
        "email": email,
        "issued_at": int(time.time()),
        "expires_at": expires_at,
        "features": features or [],
    }

    payload_json = json.dumps(payload, separators=(",", ":"))
    payload_b64 = base64.b64encode(payload_json.encode()).decode()

    signature = hmac.new(
        LICENSE_SECRET.encode(),
        payload_b64.encode(),
        hashlib.sha256
    ).hexdigest()

    return f"{payload_b64}.{signature}"
